// external imports

// internal imports

// implementation
const FACEBOOK_GRAPH_API_PAGE_PICTURE_PATH_PART = '/picture';
const FACEBOOK_GRAPH_API_PAGE_PHOTOS_PATH_PART = '/photos';
const FACEBOOK_GRAPH_API_PAGE_VIDEOS_PATH_PART = '/videos';

// exports
export {
    FACEBOOK_GRAPH_API_PAGE_PICTURE_PATH_PART,
    FACEBOOK_GRAPH_API_PAGE_PHOTOS_PATH_PART,
    FACEBOOK_GRAPH_API_PAGE_VIDEOS_PATH_PART,
}