// external imports

// internal imports

// implementation
const FACEBOOK_GRAPH_API_BASE_URL = 'https://graph.facebook.com/';
const FACEBOOK_GRAPH_VIDEO_API_BASE_URL = 'https://graph-video.facebook.com/';
const FACEBOOK_GRAPH_REELS_UPLOAD_API_BASE_URL = 'https://rupload.facebook.com/';

const FACEBOOK_GRAPH_API_DEFAULT_VERSION = 'v23.0';
const FACEBOOK_GRAPH_API_FILE_UPLOAD_DEFAULT_BUFFER_SIZE = 5242880;

const FACEBOOK_GRAPH_API_COMMON_UPLOADS_PATH_PART =  '/uploads';
const FACEBOOK_GRAPH_REELS_UPLOAD_API_VIDEO_PATH_PART = '/video-upload';

// exports
export {
    FACEBOOK_GRAPH_API_BASE_URL,
    FACEBOOK_GRAPH_VIDEO_API_BASE_URL,
    FACEBOOK_GRAPH_REELS_UPLOAD_API_BASE_URL,

    FACEBOOK_GRAPH_API_DEFAULT_VERSION,
    FACEBOOK_GRAPH_API_FILE_UPLOAD_DEFAULT_BUFFER_SIZE,

    FACEBOOK_GRAPH_API_COMMON_UPLOADS_PATH_PART,
    FACEBOOK_GRAPH_REELS_UPLOAD_API_VIDEO_PATH_PART,
}