// external imports

// internal imports

// implementation
const GCP_MONITORING_FIREBASE_HOSTING_NETWORK_MONTHLY_SENT_METRIC = 'firebasehosting.googleapis.com/network/monthly_sent';
const GCP_MONITORING_FIREBASE_HOSTING_NETWORK_MONTHLY_SENT_METRIC_PERIOD = 28800 + 4200;

const GCP_MONITORING_FIREBASE_HOSTING_NETWORK_MONTHLY_SENT_LIMIT_METRIC = 'firebasehosting.googleapis.com/network/monthly_sent_limit';
const GCP_MONITORING_FIREBASE_HOSTING_NETWORK_MONTHLY_SENT_LIMIT_METRIC_PERIOD = 28800 + 4200;

const GCP_MONITORING_FIREBASE_HOSTING_NETWORK_SENT_BYTES_COUNT_METRIC = 'firebasehosting.googleapis.com/network/sent_bytes_count';
const GCP_MONITORING_FIREBASE_HOSTING_NETWORK_SENT_BYTES_COUNT_METRIC_PERIOD = 0;

const GCP_MONITORING_FIREBASE_HOSTING_STORAGE_LIMIT_METRIC = 'firebasehosting.googleapis.com/storage/limit';
const GCP_MONITORING_FIREBASE_HOSTING_STORAGE_LIMIT_METRIC_PERIOD = 28800;

const GCP_MONITORING_FIREBASE_HOSTING_STORAGE_TOTAL_BYTES_METRIC = 'firebasehosting.googleapis.com/storage/total_bytes';
const GCP_MONITORING_FIREBASE_HOSTING_STORAGE_TOTAL_BYTES_METRIC_PERIOD = 28800;

// exports
export {
    GCP_MONITORING_FIREBASE_HOSTING_NETWORK_MONTHLY_SENT_METRIC,
    GCP_MONITORING_FIREBASE_HOSTING_NETWORK_MONTHLY_SENT_METRIC_PERIOD,

    GCP_MONITORING_FIREBASE_HOSTING_NETWORK_MONTHLY_SENT_LIMIT_METRIC,
    GCP_MONITORING_FIREBASE_HOSTING_NETWORK_MONTHLY_SENT_LIMIT_METRIC_PERIOD,

    GCP_MONITORING_FIREBASE_HOSTING_NETWORK_SENT_BYTES_COUNT_METRIC,
    GCP_MONITORING_FIREBASE_HOSTING_NETWORK_SENT_BYTES_COUNT_METRIC_PERIOD,

    GCP_MONITORING_FIREBASE_HOSTING_STORAGE_LIMIT_METRIC,
    GCP_MONITORING_FIREBASE_HOSTING_STORAGE_LIMIT_METRIC_PERIOD,

    GCP_MONITORING_FIREBASE_HOSTING_STORAGE_TOTAL_BYTES_METRIC,
    GCP_MONITORING_FIREBASE_HOSTING_STORAGE_TOTAL_BYTES_METRIC_PERIOD,
}