// external imports

// internal imports

// implementation
const GEMINI_PRO_PREVIEW_3_1_MODEL_NAME = 'gemini-3.1-pro-preview';
const GEMINI_PRO_PREVIEW_3_1_CUSTOM_TOOLS_MODEL_NAME = 'gemini-3.1-pro-preview-customtools';
const GEMINI_3_1_FLASH_LITE_PREVIEW_MODEL_NAME = 'gemini-3.1-flash-lite-preview';
const GEMINI_3_1_FLASH_IMAGE_PREVIEW_MODEL_NAME = 'gemini-3.1-flash-image-preview';

const GEMINI_3_FLASH_PREVIEW_MODEL_NAME = 'gemini-3-flash-preview';
const GEMINI_3_PRO_IMAGE_PREVIEW_MODEL_NAME = 'gemini-3-pro-image-preview';

const GEMINI_2_5_FLASH_MODEL_NAME = 'gemini-2.5-flash';
const GEMINI_2_5_FLASH_LITE_MODEL_NAME = 'gemini-2.5-flash-lite';
const GEMINI_2_5_FLASH_LITE_PREVIEW_09_2025_MODEL_NAME = 'gemini-2.5-flash-lite-preview-09-2025';
const GEMINI_2_5_FLASH_NATIVE_AUDIO_PREVIEW_12_2025 = 'gemini-2.5-flash-native-audio-preview-12-2025';
const GEMINI_2_5_FLASH_IMAGE_MODEL_NAME = 'gemini-2.5-flash-image';
const GEMINI_2_5_FLASH_PREVIEW_TTS_MODEL_NAME = 'gemini-2.5-flash-preview-tts';
const GEMINI_2_5_PRO_PREVIEW_TTS_MODEL_NAME = 'gemini-2.5-pro-preview-tts';

const IMAGEN_4_0_GENERATE_001_MODEL_NAME = 'imagen-4.0-generate-001';
const IMAGEN_4_0_ULTRA_GENERATE_001_MODEL_NAME = 'imagen-4.0-ultra-generate-001';
const IMAGEN_4_0_FAST_GENERATE_001_MODEL_NAME = 'imagen-4.0-fast-generate-001';

const VEO_3_1_GENERATE_PREVIEW_MODEL_NAME = 'veo-3.1-generate-preview';
const VEO_3_1_FAST_GENERATE_PREVIEW_MODEL_NAME = 'veo-3.1-fast-generate-preview';

const VEO_3_0_GENERATE_001_MODEL_NAME = 'veo-3.0-generate-001';
const VEO_3_0_FAST_GENERATE_001_MODEL_NAME = 'veo-3.0-fast-generate-001';

const VEO_2_0_GENERATE_001_MODEL_NAME = 'veo-2.0-generate-001';

const GEMINI_EMBEDDING_2_PREVIEW_MODEL_NAME = 'gemini-embedding-2-preview';
const GEMINI_EMBEDDING_001_MODEL_NAME = 'gemini-embedding-001';

/**
 * Multimodal understanding enables AI to process, interpret, and reason across diverse data types simultaneously—such as text, images, audio, video, and sensory
 * input—rather than relying on a single modality.
 *
 */

const MULTIMODAL_UNDERSTANDING_MODELS_NAMES = [
    GEMINI_PRO_PREVIEW_3_1_MODEL_NAME,
    GEMINI_PRO_PREVIEW_3_1_CUSTOM_TOOLS_MODEL_NAME,
];

/**
 * Agentic AI - autonomous systems that possess the capability to reason, plan, and execute multi-step tasks independently to achieve a specific goal, without
 * requiring constant human guidance.
 *
 */

const AGENTIC_MODELS_NAMES = [
    GEMINI_PRO_PREVIEW_3_1_MODEL_NAME,
    GEMINI_PRO_PREVIEW_3_1_CUSTOM_TOOLS_MODEL_NAME,
    GEMINI_3_1_FLASH_LITE_PREVIEW_MODEL_NAME,
];

const VIBE_CODING_MODELS_NAMES = [
    GEMINI_PRO_PREVIEW_3_1_MODEL_NAME,
    GEMINI_PRO_PREVIEW_3_1_CUSTOM_TOOLS_MODEL_NAME,
];

const SIMPLE_DATA_PROCESSING_MODELS_NAMES = [
    GEMINI_3_1_FLASH_LITE_PREVIEW_MODEL_NAME,
];

const TRANSLATION_MODELS_NAMES = [
    GEMINI_3_1_FLASH_LITE_PREVIEW_MODEL_NAME,
];

const IMAGE_GENERATION_MODELS_NAMES = [
    GEMINI_3_1_FLASH_IMAGE_PREVIEW_MODEL_NAME,
    GEMINI_3_PRO_IMAGE_PREVIEW_MODEL_NAME,
    GEMINI_2_5_FLASH_IMAGE_MODEL_NAME,
    IMAGEN_4_0_GENERATE_001_MODEL_NAME,
    IMAGEN_4_0_ULTRA_GENERATE_001_MODEL_NAME,
    IMAGEN_4_0_FAST_GENERATE_001_MODEL_NAME,
];

const VIDEO_GENERATION_MODELS_NAMES = [
    VEO_3_1_GENERATE_PREVIEW_MODEL_NAME,
    VEO_3_1_FAST_GENERATE_PREVIEW_MODEL_NAME,
    VEO_3_0_GENERATE_001_MODEL_NAME,
    VEO_3_0_FAST_GENERATE_001_MODEL_NAME,
    VEO_2_0_GENERATE_001_MODEL_NAME,
];

const AUDIO_PROCESSING_MODELS_NAMES = [
    GEMINI_2_5_FLASH_NATIVE_AUDIO_PREVIEW_12_2025,
];

const TEXT_TO_SPEECH_MODELS_NAMES = [
    GEMINI_2_5_FLASH_PREVIEW_TTS_MODEL_NAME,
    GEMINI_2_5_PRO_PREVIEW_TTS_MODEL_NAME,
];

const EMBEDDING_GENERATION_MODELS_NAMES = [
    GEMINI_EMBEDDING_2_PREVIEW_MODEL_NAME,
    GEMINI_EMBEDDING_001_MODEL_NAME,
];

const GENERAL_MODELS_NAMES = [
    GEMINI_3_FLASH_PREVIEW_MODEL_NAME,
    GEMINI_2_5_FLASH_MODEL_NAME,
    GEMINI_2_5_FLASH_LITE_MODEL_NAME,
    GEMINI_2_5_FLASH_LITE_PREVIEW_09_2025_MODEL_NAME,
];

// exports
export {
    GEMINI_PRO_PREVIEW_3_1_MODEL_NAME,
    GEMINI_PRO_PREVIEW_3_1_CUSTOM_TOOLS_MODEL_NAME,
    GEMINI_3_1_FLASH_LITE_PREVIEW_MODEL_NAME,
    GEMINI_3_1_FLASH_IMAGE_PREVIEW_MODEL_NAME,

    GEMINI_3_FLASH_PREVIEW_MODEL_NAME,
    GEMINI_3_PRO_IMAGE_PREVIEW_MODEL_NAME,

    GEMINI_2_5_FLASH_MODEL_NAME,
    GEMINI_2_5_FLASH_LITE_MODEL_NAME,
    GEMINI_2_5_FLASH_LITE_PREVIEW_09_2025_MODEL_NAME,
    GEMINI_2_5_FLASH_NATIVE_AUDIO_PREVIEW_12_2025,
    GEMINI_2_5_FLASH_IMAGE_MODEL_NAME,
    GEMINI_2_5_FLASH_PREVIEW_TTS_MODEL_NAME,
    GEMINI_2_5_PRO_PREVIEW_TTS_MODEL_NAME,

    IMAGEN_4_0_GENERATE_001_MODEL_NAME,
    IMAGEN_4_0_ULTRA_GENERATE_001_MODEL_NAME,
    IMAGEN_4_0_FAST_GENERATE_001_MODEL_NAME,

    VEO_3_1_GENERATE_PREVIEW_MODEL_NAME,
    VEO_3_1_FAST_GENERATE_PREVIEW_MODEL_NAME,

    VEO_3_0_GENERATE_001_MODEL_NAME,
    VEO_3_0_FAST_GENERATE_001_MODEL_NAME,

    VEO_2_0_GENERATE_001_MODEL_NAME,

    GEMINI_EMBEDDING_2_PREVIEW_MODEL_NAME,
    GEMINI_EMBEDDING_001_MODEL_NAME,

    MULTIMODAL_UNDERSTANDING_MODELS_NAMES,
    AGENTIC_MODELS_NAMES,
    VIBE_CODING_MODELS_NAMES,
    SIMPLE_DATA_PROCESSING_MODELS_NAMES,
    TRANSLATION_MODELS_NAMES,
    IMAGE_GENERATION_MODELS_NAMES,
    VIDEO_GENERATION_MODELS_NAMES,
    AUDIO_PROCESSING_MODELS_NAMES,
    TEXT_TO_SPEECH_MODELS_NAMES,
    EMBEDDING_GENERATION_MODELS_NAMES,
    GENERAL_MODELS_NAMES,
}
