'use strict';

// external imports

// internal imports

// implementation
const AVL_BINARY_SEARCH_TREE_UNBALANCED_RIGHT = 1;
const AVL_BINARY_SEARCH_TREE_SLIGHTLY_UNBALANCED_RIGHT = 2;
const AVL_BINARY_SEARCH_TREE_BALANCED = 3;
const AVL_BINARY_SEARCH_TREE_SLIGHTLY_UNBALANCED_LEFT = 4;
const AVL_BINARY_SEARCH_TREE_UNBALANCED_LEFT = 5;

// exports
export {
    AVL_BINARY_SEARCH_TREE_UNBALANCED_RIGHT,
    AVL_BINARY_SEARCH_TREE_SLIGHTLY_UNBALANCED_RIGHT,
    AVL_BINARY_SEARCH_TREE_BALANCED,
    AVL_BINARY_SEARCH_TREE_SLIGHTLY_UNBALANCED_LEFT,
    AVL_BINARY_SEARCH_TREE_UNBALANCED_LEFT,
}