'use strict';

// external imports

// internal imports

// implementation

// 0000
const COMPARATOR_NONE_EQUAL = 0;

// 0001
const COMPARATOR_EQUAL = 1;

// 0010
const COMPARATOR_LESS_THAN = 2;

// 0100
const COMPARATOR_GREATER_THAN = 4;

// 0011
const COMPARATOR_LESS_OR_EQUAL = COMPARATOR_EQUAL | COMPARATOR_LESS_THAN; // 3

// 0101
const COMPARATOR_GREATER_OR_EQUAL = COMPARATOR_EQUAL | COMPARATOR_GREATER_THAN; // 5

// exports
export {
    COMPARATOR_NONE_EQUAL,
    COMPARATOR_EQUAL,

    COMPARATOR_LESS_THAN,
    COMPARATOR_GREATER_THAN,

    COMPARATOR_LESS_OR_EQUAL,
    COMPARATOR_GREATER_OR_EQUAL,
}