// external imports

// internal imports

// implementation
const HASHING_M_PRIME_NUMBER1 = 1e9 + 7; // 1,000,000,007
const HASHING_M_PRIME_NUMBER2 = 1e9 + 9; // 1,000,000,009

const HASHING_M_MERSENNE_PRIME_NUMBER = Math.pow(2, 31) - 1; // 2,147,483,647

const HASHING_P_PRIME_NUMBER_ALPHABETIC1 = 31;
const HASHING_P_PRIME_NUMBER_ALPHABETIC2 = 53;

// exports
export {
    HASHING_M_PRIME_NUMBER1,
    HASHING_M_PRIME_NUMBER2,

    HASHING_M_MERSENNE_PRIME_NUMBER,

    HASHING_P_PRIME_NUMBER_ALPHABETIC1,
    HASHING_P_PRIME_NUMBER_ALPHABETIC2,
}