// external imports

// internal imports

// implementation
const HTTP_REQUEST_TIMEOUT = 65000;
const HTTP_REQUEST_TIMEOUT_PADDING = 5000;

const HTTP_REQUEST_TRY_ATTEMPT_MAX = 5;
const HTTP_REQUEST_TRY_ATTEMPT_DELAY = 10000;

// exports
export {
    HTTP_REQUEST_TIMEOUT,
    HTTP_REQUEST_TIMEOUT_PADDING,

    HTTP_REQUEST_TRY_ATTEMPT_MAX,
    HTTP_REQUEST_TRY_ATTEMPT_DELAY,
}