// external imports

// internal imports

// implementation
const HTTP_REQUEST_TIMEOUT = 65000;
const HTTP_REQUEST_TIMEOUT_PADDING = 5000;

const HTTP_REQUEST_TRY_ATTEMPT_MAX = 5;
const HTTP_REQUEST_TRY_ATTEMPT_DELAY = 10000;

const HTTP_REQUEST_DATA_MAX_CHUNK_SIZE = 1048576;

const HTTP_DEFAULT_AUTHORIZATION_HEADER_NAME = 'Authorization';

// exports
export {
    HTTP_REQUEST_TIMEOUT,
    HTTP_REQUEST_TIMEOUT_PADDING,

    HTTP_REQUEST_TRY_ATTEMPT_MAX,
    HTTP_REQUEST_TRY_ATTEMPT_DELAY,

    HTTP_REQUEST_DATA_MAX_CHUNK_SIZE,
    HTTP_DEFAULT_AUTHORIZATION_HEADER_NAME,
}