// external imports

// internal imports

// implementation
const API_REQUEST_ENTITIES_INITIAL_PAGE = 1;
const API_REQUEST_ENTITIES_LIMIT = 20;

const API_REQUEST_SIMULTANEOUS_CONNECTIONS_LIMIT = 5;

// exports
export {
    API_REQUEST_ENTITIES_INITIAL_PAGE,
    API_REQUEST_ENTITIES_LIMIT,

    API_REQUEST_SIMULTANEOUS_CONNECTIONS_LIMIT,
}