// external imports

// internal imports

// implementation
const GCP_MAX_AGGREGATED_RESULTS_PER_PAGE = 25;

const GCP_OPERATION_CHECK_RETRIES_COUNT = 10;
const GCP_OPERATION_CHECK_TIMEOUT = 5000; // ms
const GCP_OPERATION_CHECK_DELAY = 3000; // ms

// exports
export {
    GCP_MAX_AGGREGATED_RESULTS_PER_PAGE,

    GCP_OPERATION_CHECK_RETRIES_COUNT,
    GCP_OPERATION_CHECK_TIMEOUT,
    GCP_OPERATION_CHECK_DELAY,
}