// external imports

// internal imports

// implementation
const PLAIN_TEXT_ENCRYPTOR_NAME = 'PLAIN_TEXT';
const CHA_CHA20_POLY1305_BASE64_ENCRYPTOR_NAME = 'CHA_CHA20_POLY1305_BASE64';

// exports
export {
    PLAIN_TEXT_ENCRYPTOR_NAME,
    CHA_CHA20_POLY1305_BASE64_ENCRYPTOR_NAME,
}