// external imports

// internal imports
import {
    META_MIME_TYPE_VIDEO,

    MIME_TYPE_APNG,
    MIME_TYPE_JPG,
    MIME_TYPE_JPEG,
    MIME_TYPE_SVG,
    MIME_TYPE_GIF,

    MIME_TYPE_3G2,
    MIME_TYPE_3GP,
    MIME_TYPE_ASF,
    MIME_TYPE_AVI,
    MIME_TYPE_DIVX,
    MIME_TYPE_DV,
    MIME_TYPE_F4V,
    MIME_TYPE_FLV,
    MIME_TYPE_M2TS,
    MIME_TYPE_M4V,
    MIME_TYPE_MATROSKA,
    MIME_TYPE_MOD,
    MIME_TYPE_MOV,
    MIME_TYPE_MP4,
    MIME_TYPE_MPEG,
    MIME_TYPE_NSV,
    MIME_TYPE_OGV,
    MIME_TYPE_QUICKTIME,
    MIME_TYPE_VOB,
} from '../net/common/mime_types_constants';

// implementation
const UPLOAD_ALLOWED_DEFAULT_IMAGE_SIZE = 31 * 1024 * 1024; // 31 mb
const UPLOAD_ALLOWED_DEFAULT_VIDEO_SIZE = 1024 * 1024 * 1024; // 1 gb

const UPLOAD_ALLOWED_DEFAULT_IMAGE_FILES_LIST = [
    MIME_TYPE_APNG,
    MIME_TYPE_JPG,
    MIME_TYPE_JPEG,
    MIME_TYPE_SVG,
    MIME_TYPE_GIF,
];

const UPLOAD_ALLOWED_DEFAULT_VIDEO_FILES_LIST = [
    MIME_TYPE_3G2[META_MIME_TYPE_VIDEO],
    MIME_TYPE_3GP[META_MIME_TYPE_VIDEO],
    MIME_TYPE_ASF[META_MIME_TYPE_VIDEO],
    MIME_TYPE_AVI,
    MIME_TYPE_DIVX,
    MIME_TYPE_DV,
    MIME_TYPE_F4V,
    MIME_TYPE_FLV,
    MIME_TYPE_GIF,
    MIME_TYPE_M2TS,
    MIME_TYPE_M4V,
    MIME_TYPE_MATROSKA,
    MIME_TYPE_MOD[0],
    MIME_TYPE_MOD[1],
    MIME_TYPE_MOV,
    MIME_TYPE_MP4,
    MIME_TYPE_MPEG,
    MIME_TYPE_NSV[0],
    MIME_TYPE_NSV[1],
    MIME_TYPE_OGV,
    MIME_TYPE_QUICKTIME,
    MIME_TYPE_VOB,
];

// exports
export {
    UPLOAD_ALLOWED_DEFAULT_IMAGE_SIZE,
    UPLOAD_ALLOWED_DEFAULT_VIDEO_SIZE,

    UPLOAD_ALLOWED_DEFAULT_IMAGE_FILES_LIST,
    UPLOAD_ALLOWED_DEFAULT_VIDEO_FILES_LIST,
}