// external imports

// internal imports
import {
    MIME_TYPE_3DOSTR,
    MIME_TYPE_3G2,
    MIME_TYPE_3GP,
    MIME_TYPE_4XM,
    MIME_TYPE_A64,
    MIME_TYPE_AA,
    MIME_TYPE_AAC,
    MIME_TYPE_AC3,
    MIME_TYPE_ACM,
    MIME_TYPE_ADTS,
    MIME_TYPE_AIFF,
    MIME_TYPE_AMR,
    MIME_TYPE_APNG,
    MIME_TYPE_ASF,
    MIME_TYPE_ASF_STREAM,
    MIME_TYPE_ASS,
    MIME_TYPE_AU,
    MIME_TYPE_AVI,
    MIME_TYPE_AVM2,
    MIME_TYPE_BIN,
    MIME_TYPE_BIT,
    MIME_TYPE_CAF,
    MIME_TYPE_DTS,
    MIME_TYPE_DVD,
    MIME_TYPE_EAC3,
    MIME_TYPE_F4V,
    MIME_TYPE_FLAC,
    MIME_TYPE_FLV,
    MIME_TYPE_G722,
    MIME_TYPE_G723_1,
    MIME_TYPE_GIF,
    MIME_TYPE_GSM,
    MIME_TYPE_H261,
    MIME_TYPE_H263,
    MIME_TYPE_HLS,
    MIME_TYPE_APPLE_HTTP,
    MIME_TYPE_ICO,
    MIME_TYPE_ILBC,
    MIME_TYPE_IPOD,
    MIME_TYPE_ISMV,
    MIME_TYPE_JACOSUB,
    MIME_TYPE_JPEG_PIPE,
    MIME_TYPE_JPEGLS_PIPE,
    MIME_TYPE_LATM,
    MIME_TYPE_LIVE_FLV,
    MIME_TYPE_M4V,
    MIME_TYPE_MATROSKA,
    MIME_TYPE_MICRODVD,
    MIME_TYPE_MJPEG,
    MIME_TYPE_MJPEG_2000,
    MIME_TYPE_MMF,
    MIME_TYPE_MP2,
    MIME_TYPE_MP3,
    MIME_TYPE_MP4,
    MIME_TYPE_MPEG,
    MIME_TYPE_MPEG1VIDEO,
    MIME_TYPE_MPEG2VIDEO,
    MIME_TYPE_MPEGTS,
    MIME_TYPE_MPEGTSRAW,
    MIME_TYPE_MPEGVIDEO,
    MIME_TYPE_MPJPEG,
    MIME_TYPE_MXF,
    MIME_TYPE_MXF_D10,
    MIME_TYPE_MXF_OPATOM,
    MIME_TYPE_NUT,
    MIME_TYPE_OGA,
    MIME_TYPE_OGG,
    MIME_TYPE_OGV,
    MIME_TYPE_OMA,
    MIME_TYPE_OPUS,
    MIME_TYPE_RM,
    MIME_TYPE_SINGLEJPEG,
    MIME_TYPE_SMJPEG,
    MIME_TYPE_SPX,
    MIME_TYPE_SRT,
    MIME_TYPE_SUP,
    MIME_TYPE_SVCD,
    MIME_TYPE_SWF,
    MIME_TYPE_TTA,
    MIME_TYPE_VCD,
    MIME_TYPE_VOB,
    MIME_TYPE_VOC,
    MIME_TYPE_WAV,
    MIME_TYPE_WEBM,
    MIME_TYPE_WEBM_CHUNK,
    MIME_TYPE_WEBM_DASH_MANIFEST,
    MIME_TYPE_WEBP,
    MIME_TYPE_WEBVTT,
    MIME_TYPE_WV,
} from '../net/common/mime_types_constants';

// implementation
const FFMPEG_FORMAT_TO_MIME_TYPE = {
    '3dostr': MIME_TYPE_3DOSTR,
    '3g2': MIME_TYPE_3G2,
    '3gp': MIME_TYPE_3GP,
    '4xm': MIME_TYPE_4XM,
    'a64': MIME_TYPE_A64,
    'aa': MIME_TYPE_AA,
    'aac': MIME_TYPE_AAC,
    'ac3': MIME_TYPE_AC3,
    'acm': MIME_TYPE_ACM,
    'adts': MIME_TYPE_ADTS,
    'aiff': MIME_TYPE_AIFF,
    'amr': MIME_TYPE_AMR,
    'apng': MIME_TYPE_APNG,
    'asf': MIME_TYPE_ASF,
    'asf_stream': MIME_TYPE_ASF_STREAM,
    'ass': MIME_TYPE_ASS,
    'au': MIME_TYPE_AU,
    'avi': MIME_TYPE_AVI,
    'avm2': MIME_TYPE_AVM2,
    'bin': MIME_TYPE_BIN,
    'bit': MIME_TYPE_BIT,
    'caf': MIME_TYPE_CAF,
    'dts': MIME_TYPE_DTS,
    'dvd': MIME_TYPE_DVD,
    'eac3': MIME_TYPE_EAC3,
    'f4v': MIME_TYPE_F4V,
    'flac': MIME_TYPE_FLAC,
    'flv': MIME_TYPE_FLV,
    'g722': MIME_TYPE_G722,
    'g723_1': MIME_TYPE_G723_1,
    'gif': MIME_TYPE_GIF,
    'gsm': MIME_TYPE_GSM,
    'h261': MIME_TYPE_H261,
    'h263': MIME_TYPE_H263,
    'hls': MIME_TYPE_HLS,
    'applehttp,hls': MIME_TYPE_HLS,
    'applehttp': MIME_TYPE_APPLE_HTTP,
    'ico': MIME_TYPE_ICO,
    'ilbc': MIME_TYPE_ILBC,
    'ipod': MIME_TYPE_IPOD,
    'ismv': MIME_TYPE_ISMV,
    'jacosub': MIME_TYPE_JACOSUB,
    'jpeg_pipe': MIME_TYPE_JPEG_PIPE,
    'jpegls_pipe': MIME_TYPE_JPEGLS_PIPE,
    'latm': MIME_TYPE_LATM,
    'live_flv': MIME_TYPE_LIVE_FLV,
    'm4v': MIME_TYPE_M4V,
    'matroska': MIME_TYPE_MATROSKA,
    'matroska,webm': MIME_TYPE_WEBM,
    'microdvd': MIME_TYPE_MICRODVD,
    'mjpeg': MIME_TYPE_MJPEG,
    'mjpeg_2000': MIME_TYPE_MJPEG_2000,
    'mmf': MIME_TYPE_MMF,
    '3g2,3gp,m4a,mj2,mov,mp4': MIME_TYPE_MP4,
    'mp2': MIME_TYPE_MP2,
    'mp3': MIME_TYPE_MP3,
    'mp4': MIME_TYPE_MP4,
    'mpeg': MIME_TYPE_MPEG,
    'mpeg1video': MIME_TYPE_MPEG1VIDEO,
    'mpeg2video': MIME_TYPE_MPEG2VIDEO,
    'mpegts': MIME_TYPE_MPEGTS,
    'mpegtsraw': MIME_TYPE_MPEGTSRAW,
    'mpegvideo': MIME_TYPE_MPEGVIDEO,
    'mpjpeg': MIME_TYPE_MPJPEG,
    'mxf': MIME_TYPE_MXF,
    'mxf_d10': MIME_TYPE_MXF_D10,
    'mxf_opatom': MIME_TYPE_MXF_OPATOM,
    'nut': MIME_TYPE_NUT,
    'oga': MIME_TYPE_OGA,
    'ogg': MIME_TYPE_OGG,
    'ogv': MIME_TYPE_OGV,
    'oma': MIME_TYPE_OMA,
    'opus': MIME_TYPE_OPUS,
    'rm': MIME_TYPE_RM,
    'singlejpeg': MIME_TYPE_SINGLEJPEG,
    'smjpeg': MIME_TYPE_SMJPEG,
    'spx': MIME_TYPE_SPX,
    'srt': MIME_TYPE_SRT,
    'sup': MIME_TYPE_SUP,
    'svcd': MIME_TYPE_SVCD,
    'swf': MIME_TYPE_SWF,
    'tta': MIME_TYPE_TTA,
    'vcd': MIME_TYPE_VCD,
    'vob': MIME_TYPE_VOB,
    'voc': MIME_TYPE_VOC,
    'wav': MIME_TYPE_WAV,
    'webm': MIME_TYPE_WEBM,
    'webm_chunk': MIME_TYPE_WEBM_CHUNK,
    'webm_dash_manifest': MIME_TYPE_WEBM_DASH_MANIFEST,
    'webp': MIME_TYPE_WEBP,
    'webvtt': MIME_TYPE_WEBVTT,
    'wv': MIME_TYPE_WV,
};

// exports
export default FFMPEG_FORMAT_TO_MIME_TYPE;